package com.marcos.hiber;
// Generated 22 May, 2020 4:52:56 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Country generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "country", catalog = "springboot")
public class Country implements java.io.Serializable {

	private Integer cid;
	private String cname;
//	private Set<Employee> employees = new HashSet<>(0);

	public Country() {
	}

	public Country(String cname) {
		this.cname = cname;
	}

//	public Country(String cname, Set<Employee> employees) {
//		this.cname = cname;
//		this.employees = employees;
//	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cid", unique = true, nullable = false)
	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	@Column(name = "cname", nullable = false, length = 45)
	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	@Override
	public String toString() {
		return "Country [cid=" + cid + ", cname=" + cname + "]";
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
//	public Set<Employee> getEmployees() {
//		return this.employees;
//	}
//
//	public void setEmployees(Set<Employee> employees) {
//		this.employees = employees;
//	}

}
